import type { Metadata } from "next";
import Link from "next/link";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable}`}>
      <body>
        <header>
          <Link href="/" title="Le Cheffon Fat">
            🧑‍🍳
          </Link>
        </header>
        <main>{children}</main>
        <aside>
          <p>Here the aside</p>
        </aside>
        <footer>
          <p>
            Made with 🥄 by{" "}
            <Link href="https://github.com/CoachGodzup">Matteo Garza</Link>
          </p>
        </footer>
      </body>
    </html>
  );
}
